import type { Metadata } from "next";
import { AuthProvider } from "./providers/AuthProvider";
import { initAuth } from "@/shared/api/auth/InitAuth";
import "./globals.css";
import { Roboto } from "next/font/google";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700", "800"],
  variable: "--font-roboto",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`antialiased`}>
      <body className={`${roboto.variable}`}>
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
